### ISSUE TITLE
Readme is out of date for npm install

### ISSUE THREAD

**Issue by alexnitta** [fauna-labs/fauna-schema-migrate#101]
It looks like this package was moved in npm, such that the correct `npm install` command is:

```
npm install @fauna-labs/fauna-schema-migrate
```

but the readme still says to do:

```
npm install fauna-schema-migrate
```

Also, there's still a description in the readme about:
> By using this repository or its contents, you agree that this repository may never be officially supported and moved to the Fauna organization.

but it looks like this repository was indeed moved to the Fauna organization.

**Comment by rts-rob** [comment]
Thanks for finding and submitting, @alexnitta !

I've submitted #102 which corrects the installation command.

Regarding the description, all [Fauna Labs](https://github.com/fauna-labs) repos are unofficial. Official/full support refers to the [Fauna GitHub organization](https://github.com/fauna).

If you'd like to see Fauna Schema Migrate officially supported, please add your thumbs up to #54 along with any specific features you'd like to see integrated!

Thanks again for the contribution.

**Comment by alexnitta** [comment]
I see, thanks for clarifying! I've added my vote to https://github.com/fauna-labs/fauna-schema-migrate/issues/54.
