### ISSUE TITLE
`Containsstr is not defined` error when ContainsStr() function is used in a UDF

### ISSUE THREAD

**Issue by zeekhoo** [fauna-labs/fauna-schema-migrate#103]
Using the built in function in a UDF definition. The migration file transposes it to all lowercase: `Containsstr`. 

After fixing the migration file manually by correcting `Containsstr` back to `ContainsStr`, running the the `apply` command gives us the error:

```
ReferenceError: Containsstr is not defined 
```

**Comment by rts-rob** [comment]
Thank you for this submission. 

This is a JavaScript driver error; follow https://github.com/fauna/faunadb-js/issues/521 for additional details.
