### ISSUE TITLE
a CHANGELOG will be great...

### ISSUE THREAD

**Issue by aprilmintacpineda** [fauna-labs/fauna-schema-migrate#43]
ref https://keepachangelog.com/

**Comment by fauna-brecht** [comment]
Thanks for the suggestion, we'll start keeping one going forward.

**Comment by aprilmintacpineda** [comment]
Because I wanted to keep my dependencies always up to date as much as possible but that's gonna be hard to do without knowing what changed in that version that I am updating to...

**Comment by Shadid12** [comment]
changelog script is in place.
