### ISSUE TITLE
Add flag to ignore UndefinedReferenceError

### ISSUE THREAD

**Issue by chronark** [fauna-labs/fauna-schema-migrate#49]
I would like to use this tool to add resolvers and other functions after uploading a graphql schema.
Unfortunately this will throw an error because lots of collections etc are not defined in `resources`

I came accross this little todo and wanted to implement a flag but I am completely lost where to even start. I browsed the code but could not figure out where the flags are actually being used. 
```
The following resource is not defined anywhere in the resource folders
      type: Collection, name: accounts
  and was referenced from:
      type: Index, name: account_by_email
  
  todo: add a boolean to bypass this error in case users
        want to reference resources that were defined manually.
```

The function for checking is being called [here](https://github.com/fauna-labs/fauna-schema-migrate/blob/13af108611722548e13d557358a358a045b45be0/src/migrations/plan.ts#L49) but that's as far as I got.

Could you help me figure this out, so I can submit a PR.

Thanks and have a great day

**Comment by fauna-brecht** [comment]
Thanks for the suggestion, when thinking of adding GraphQL support I was thinking along the same lines as one of the options.
