### ISSUE TITLE
Erroneous undefined reference errors

### ISSUE THREAD

**Issue by rachaelmcq** [fauna-labs/fauna-schema-migrate#78]
When I try to generate migrations, I get errors claiming the resources "[aren't] defined anywhere in the resource folders". For the following `fauna/resources/functions.fql`: 
```
CreateFunction({
  name: "A",
  role: "server",
  body: Query(
    Lambda(
      "",
      true
    )
  )
})
CreateFunction({
  name: "B",
  role: "server",
  body: Query(
    Lambda(
      "",
      Call(Function("A"), []),
    )
  )
})
```

I get the error: 
```
! Error:
      The following resource is not defined anywhere in the resource folders
          type: Function, name: A
      and was referenced from:
          type: Function, name: B
```

However, if I swap the order I declare these functions in:
```
CreateFunction({
  name: "B",
  role: "server",
  body: Query(
    Lambda(
      "",
      Call(Function("A"), []),
    )
  )
})
CreateFunction({
  name: "A",
  role: "server",
  body: Query(
    Lambda(
      "",
      true
    )
  )
})
```
I have no problems. This is true of every resource I'm creating that references another resource, and across files as well. Depending on defining them in reverse order and then having the error say depended-on resources aren't "anywhere in the resource folders" is pretty confusing.

**Comment by rachaelmcq** [comment]
Seems like the workaround here might be to define every resource in its own file.

**Comment by databrecht** [comment]
Hey @rachaelmcq, it's not really a workaround, it's intended to work like that.
There is only one resource expected in each file.

**Comment by rachaelmcq** [comment]
Ah, I missed that. Yeah, a warning about multiple resources in one file would help.
